language: python

cache: pip

python:
  - "3.5"

os: linux

dist: trusty

sudo: required

before_install:
  - sudo apt-get update
  # Setup conda (needed for opencv, ray dependency)
  # WARNING: enforces py3.5
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - python -V

  # Set up requirements for running tests
  - conda env create -f environment.yml
  - source activate causal

  # install ray and copy over the desired changes
  - pip install https://s3-us-west-1.amazonaws.com/flow.utils/ray-0.6.0-cp35-cp35m-manylinux1_x86_64.whl
  - pip install redis~=2.10.6

  # Copy over local rllib changes
  - pwd
  - ls
  - pushd $HOME/build/eugenevinitsky
  -     git clone https://github.com/natashamjaques/ray.git
  -     cd ray && git fetch && git checkout master && cd ..
  -     pushd ray
  -         RAY_SITE_DIR=`python -c "import ray; print(ray.__path__[0])"`
  -         rm -rf $RAY_SITE_DIR/rllib
  -         ls $RAY_SITE_DIR
  -         cp -r python/ray/rllib $RAY_SITE_DIR/rllib
  -     popd
  - popd

install:
  - pip install flake8 .
  - pip install pytest

before_script:
  - flake8 --version
  - flake8 --show-source

script:
  - python setup.py install
  - python -m pytest

