name: causal

dependencies:
    - python==3.6.6
    - pip:
        - numpy==1.16.0
        - gym==0.10.9
        - matplotlib==3.0.2
        - opencv-python
        - ray==0.7.5
        - tensorflow==1.14.0
        - scipy==1.2.0
        - setproctitle
        - psutil
        - lz4
        - boto3==1.4.8
        - redis==3.3.2
        - pytz

