name: causal

dependencies:
    - python==3.6.8
    - pip:
        - numpy==1.14.0
        - gym==0.10.5
        - matplotlib==3.0.2
        - opencv-python
        - ray==0.6.3
        - tensorflow==1.12.0
        - scipy==1.2.0
        - setproctitle
        - psutil
        - lz4
        - boto3
